version: "3.9"
services:
    app:
        build:
            context: ./app
            dockerfile: Dockerfile
        volumes:
            - ./db:/usr/db
        working_dir: /usr/app
        command: "poetry run gunicorn financez.wsgi"
        network_mode: "host"

    ui:
        build:
            context: ./ui
            dockerfile: 'Dockerfile'
        ports:
            - 80:80
        command: [nginx, '-g', 'daemon off;']
