version: "3.9"
services:
    app:
        build:
            dockerfile: Dockerfile
        working_dir: /usr/app
        command: "poetry run gunicorn financez.wsgi:application --bind 0.0.0.0:8000"
        volumes:
            - ./db:/usr/db
            - static_volume:/srv/static/financez
        expose:
            - 8000
        env_file:
            - .env

    nginx:
        image: nginx:latest
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
            - static_volume:/srv/static/financez
        ports:
            - 80:80
        depends_on:
            - app

volumes:
    static_volume:
