# Generated by Django 3.0 on 2020-01-20 16:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('order', models.IntegerField(blank=True, default=0)),
                ('acc_type', models.CharField(choices=[('a', 'active'), ('p', 'passive')], default='a', max_length=1)),
                ('results', models.CharField(blank=True, choices=[('ast', 'assets'), ('inc', 'incomes'), ('exp', 'expenses'), ('dbt', 'debts'), ('pln', 'planning')], max_length=3, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='financez.Account')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('selected', models.BooleanField(blank=True, default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total', models.FloatField(default=0.0)),
                ('comment', models.CharField(blank=True, default='', max_length=1024)),
                ('acc_cr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acc_cr', to='financez.Account')),
                ('acc_dr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acc_dr', to='financez.Account')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financez.Currency')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Entries',
            },
        ),
        migrations.CreateModel(
            name='AccountBalance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=3, default=0.0, max_digits=15)),
                ('acc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financez.Account')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financez.Currency')),
            ],
        ),
    ]
