# Generated by Django 3.0 on 2019-12-23 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financez', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
