# Generated by Django 3.0 on 2020-01-20 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financez', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'verbose_name': 'Entry', 'verbose_name_plural': 'Entries'},
        ),
        migrations.AlterField(
            model_name='account',
            name='acc_type',
            field=models.CharField(choices=[('a', 'active'), ('p', 'passive')], default='a', max_length=1, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='account',
            name='order',
            field=models.IntegerField(blank=True, default=0, verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='account',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='financez.Account', verbose_name='parent'),
        ),
        migrations.AlterField(
            model_name='account',
            name='results',
            field=models.CharField(blank=True, choices=[('ast', 'assets'), ('inc', 'incomes'), ('exp', 'expenses'), ('dbt', 'debts'), ('pln', 'planning')], max_length=3, null=True, verbose_name='results'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='selected',
            field=models.BooleanField(blank=True, default=False, verbose_name='selected'),
        ),
    ]
