# Generated by Django 3.0 on 2020-01-20 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financez', '0002_auto_20200120_1913'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currency',
            options={'verbose_name': 'Currency', 'verbose_name_plural': 'Currencies'},
        ),
    ]
