# Generated by Django 3.0 on 2019-12-23 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financez', '0002_auto_20191223_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='acc_type',
            field=models.CharField(choices=[('a', 'active'), ('p', 'passive')], default='a', max_length=1),
        ),
    ]
