# Generated by Django 3.0 on 2019-12-23 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financez', '0003_account_acc_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='curency',
            new_name='currency',
        ),
    ]
