# Generated by Django 3.0 on 2019-12-25 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financez', '0006_account_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'verbose_name_plural': 'Entries'},
        ),
        migrations.AlterField(
            model_name='entry',
            name='comment',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
