# Generated by Django 3.0 on 2019-12-25 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financez', '0007_auto_20191225_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
    ]
