# Generated by Django 3.0 on 2019-12-26 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financez', '0009_accountbalance_accountturnovers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountbalance',
            name='date',
        ),
    ]
