# Generated by Django 3.0 on 2019-12-26 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financez', '0010_remove_accountbalance_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountbalance',
            name='total',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=15),
        ),
    ]
