# Generated by Django 3.0 on 2019-12-27 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financez', '0011_auto_20191226_1530'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountTurnover',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_dr', models.DecimalField(decimal_places=3, default=0.0, max_digits=15)),
                ('total_cr', models.DecimalField(decimal_places=3, default=0.0, max_digits=15)),
                ('acc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financez.Account')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financez.Currency')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financez.Entry')),
            ],
        ),
        migrations.DeleteModel(
            name='AccountTurnovers',
        ),
    ]
