# Generated by Django 3.0 on 2019-12-28 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financez', '0012_auto_20191227_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='results',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='formed_by', to='financez.Account'),
        ),
        migrations.AlterField(
            model_name='account',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='financez.Account'),
        ),
    ]
