# Generated by Django 3.0 on 2020-01-03 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financez', '0015_auto_20191228_1153'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='code',
            new_name='order',
        ),
        migrations.AlterField(
            model_name='account',
            name='results',
            field=models.CharField(blank=True, choices=[('ast', 'assets'), ('inc', 'incomes'), ('exp', 'expenses'), ('dbt', 'debts'), ('pln', 'planning')], max_length=3, null=True),
        ),
    ]
