# Generated by Django 3.0 on 2020-01-04 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financez', '0016_auto_20200103_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='order',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
